### ISSUE TITLE
error CS0246: The type or namespace name `Windows' could not be found.

### ISSUE THREAD

**Issue by lightofaugust** [SoylentGraham/Websocket-Sharp-UWP#1]
Hi, 

I was trying to use your file for a hololens project. The problem is, the websocketSharp namespace can't be found by the project because of the #if WINDOWS_UWP directives, the code was initially ignored. But when I manually define the #define CUSTOM_WEBSOCKET, then unity and VS give error about can't find the Windows namespace and MessageWebSocket namespace and all that. I searched some stuff on line, someone else also face this paradox. How did you manage to compile it or do you have any insight of this?

Thank you so very much!

**Comment by dvargasfr** [comment]
Same problem here. Did you solve it? Thank you!

**Comment by DorianTona** [comment]
Also same here, if someone found a workaround I'll be thankful !

**Comment by SoylentGraham** [comment]
This code is ONLY for the UWP (hololens) platform.
The windows namespace doesnt exist on another platform, hence the ifdef.

If you want websocketsharp on another platform (osx, windows, android, ios, etc) you have to add the original websocketsharp (see the project readme)

This code is more like an add on to support hololens, as UWP doesnt support the standard .net websocket implementations
