### ISSUE TITLE
Missing definition of "Connect"

### ISSUE THREAD

**Issue by Weimmer** [SoylentGraham/Websocket-Sharp-UWP#5]
Hi,
i am using the websocketsharp to connet HoloLens and ROS(Robot Operating System) with [ROSBridgeLib](https://github.com/MathiasCiarlo/ROSBridgeLib) , it works perfect in Unity, but once i deploy the app to HoloLens it dose not work, that is why i am here, i think your code would do me a favor.

when i build the app into HoloLens, it got the error: 
Error	CS1061	'WebSocket' does not contain a definition for 'Connect' and no accessible extension method 'Connect' accepting a first argument of type 'WebSocket' could be found (are you missing a using directive or an assembly reference?)	Assembly-CSharp, Assembly-CSharp.Player

i think there might be a definition for "Connect" function in websocketsharp, and might not be in your code or maybe you have renamed it.

Thanks in advance:)

**Comment by SoylentGraham** [comment]
I never implemented a `Connect()` function, as there isn't really synchronous option with the UWP websockets.

You should switch to using `ConnectAsync()` really (and move things around to be asynchronous anyway)

We could add a `Connect()` for API completeness, but it would work differently to desktop/websocketsharp which isn't really what anyone wants :)

**Comment by SoylentGraham** [comment]
In the case of ROSBridgeLib, it looks like maybe it'll be fine if `Connect()` just calls `ConnectAsync()`.
You could either add it to this code, or change the ROS lib...

Give it a try and see if it still works, or if the ROS lib needs some refactoring to be more asynchronous (ie, if it fails to connect, will it get stuck, as `Connect()` is expected to fail immediately)

**Comment by Weimmer** [comment]
@SoylentGraham Thanks a lot for your answer:)
i have just tried (some idea with change the  `Connect()` to `ConnectAsync()` ) but it did not work.
There are two things want to ask you:
1. i can not delete the `websocketsharp.dll` because it will get errors when it run in Unity, so i keep both of them in my scene(maybe it is not right).
2. when i connect with websocket, it reduce the fps immediately, is it normal?
Thanks in advance:)

**Comment by SoylentGraham** [comment]
>  can not delete the websocketsharp.dll because it will get errors when it run in Unity, so i keep both of them in my scene(maybe it is not right).

What's the question here? :)
Try not deleting your dll!

If the problem is something like, you don't want it on a platform, then tick the appropriate output targets in the inspector for a DLL and it won't output for that platform.

**Comment by SoylentGraham** [comment]
> when i connect with websocket, it reduce the fps immediately, is it normal?
Nope, it should run at 60fps, last time I used it (a couple of years ago) I happily sent and recieved data at 60.

Are you doing anything else? (receiving data, sending data?)

**Comment by Weimmer** [comment]
> > can not delete the websocketsharp.dll because it will get errors when it run in Unity, so i keep both of them in my scene(maybe it is not right).
> 
> What's the question here? :)
> Try not deleting your dll!
> 
> If the problem is something like, you don't want it on a platform, then tick the appropriate output targets in the inspector for a DLL and it won't output for that platform.
i am not sure if it would occur problem or not, when i keep both of them in my sence.

**Comment by Weimmer** [comment]
> > when i connect with websocket, it reduce the fps immediately, is it normal?
> > Nope, it should run at 60fps, last time I used it (a couple of years ago) I happily sent and recieved data at 60.
> 
> Are you doing anything else? (receiving data, sending data?)

Yes, i was reciving data from ROS, maybe that is the problem, i gonna to test it tomorrow.
Thanks a lot :)

**Comment by Weimmer** [comment]
> 
> 
> > when i connect with websocket, it reduce the fps immediately, is it normal?
> > Nope, it should run at 60fps, last time I used it (a couple of years ago) I happily sent and recieved data at 60.
> 
> Are you doing anything else? (receiving data, sending data?)

Hallo,
i did a test just now, it still dose not work, even i cancel the motion of receive data.
One thing is very strange, once i click connect, the fps reduce to like 10(before was 40), do  you have any idee about that?
And is there a definition like `Readystate` in `websocketsharp` within your code? if yes would be helpful.

**Comment by SoylentGraham** [comment]
I'm afraid without looking at all of your code, I can't really guess what the problem is.

I would suggest making an empty project, make a socket connect. 
Don't send any data to it from the server, don't do any other code, and see what happens to the frame rate. 
The code is pretty basic (as you can see) there shouldn't really be much going on, but I don't know what the UWP/OS code is doing underneath.

There is no readystate in this code. If you want to know if things have connected, or failed, use the events (`OnClose`, `OnOpen` etc)

**Comment by Weimmer** [comment]
@SoylentGraham 
Thanks a lot for your useful replies :)
Finally i found the problem is because of the firewall.
once the right connection is build, no reduce of fps, but if the ip address is wrong, then the fps just get very low.
Thank yuo again.
