### ISSUE TITLE
About OnMessage.RawData

### ISSUE THREAD

**Issue by Weimmer** [SoylentGraham/Websocket-Sharp-UWP#6]
Hi @SoylentGraham ,
me again :)
i would like to ask you about the `OnMessage.RawData` in websocketsharp, when i debug.log the message from that, it is type byte array (exactly what i want, because i need to compress the PointCloud data to byte), is it come from the other side of websocket? i mean i was told the rosbridge send the JSON data, i am confused about where comes the byte array from? it is just "raw data"?
Thanks in advance

**Comment by SoylentGraham** [comment]
So websocket's send a block of data (`byte[]`), all sockets do (all data is just `byte[]`'s underneath).
Websockets actually encode & crc check the data, but that's irrelevent (it's all done for you)

Websockets also specify if the message is binary or text. In websocketsharp, `rawData` is a binary array,(binary messages) and `data` is a string (text messages).

In my version, I only set one or the other. Websocket sharp does a conversion.

see https://github.com/sta/websocket-sharp/blob/master/websocket-sharp/MessageEventArgs.cs#L164
and mine https://github.com/SoylentGraham/Websocket-Sharp-UWP/blob/master/UwpWebsocket.cs#L51


I'm not sure what your actual question is :) but using my code, if `rawData` is set, the data is binary, if only `data` then it's text.
I can't speak for rosbridge, but if it's supposed to be sending JSON, and the message is NOT a string/data, then either they're sending the string as binary (and maybe you can just cast it to a string of char's) or it's not a JSON string (maybe it's some pointcloud data, or maybe it's compressed, or something else)

If you're expecting a string, but getting `byte[]`, debug it and see whats inside, or maybe convert to a string and print that out and see if it's some json string :)

**Comment by Weimmer** [comment]
@SoylentGraham Thanks again, i think i have something misunderstood with websocket before, your answer helps a lot :)
